# Incomplete defendant cell - missing height
def output_13145235():
    return {'case type': 'Adult Misdemeanor',
            'charge information': [{'charges': 'ASSAULT CAUSES BODILY INJURY FAMILY '
                                                'MEMBER',
                                    'date': '05/05/2019',
                                    'level': 'Misdemeanor A',
                                    'statute': '22.01(a)(1)'}],
            'code': '20-2423CR-1',
            'date filed': '06/09/2020',
            'dispositions': [],
            'location': 'County Court at Law #1',
            'name': 'The State of Texas vs. Garrett Mitchell Daniels',
            'odyssey id': '13145235',
            'other events and hearings': [['06/09/2020',
                                            'Complaint & Information (Open Case)'],
                                        ['06/11/2020',
                                            'Order for Summons',
                                            '(Judicial Officer: Updegrove, Robert )'],
                                        ['06/11/2020',
                                            'Summons',
                                            'Daniels, Garrett Mitchell',
                                            'Served',
                                            '06/11/2020'],
                                        ['11/17/2020',
                                            'CANCELED',
                                            'Arraignment',
                                            '(9:00 AM) (Judicial Officers Updegrove, '
                                            'Robert, Glickler, David)',
                                            'Reset'],
                                        ['12/09/2020',
                                            'Arraignment',
                                            '(9:00 AM) (Judicial Officers Updegrove, '
                                            'Robert, Glickler, David)',
                                            'Result: Arraigned'],
                                        ['02/25/2021', 'Discovery Receipt'],
                                        ['02/26/2021', 'Certificate of Contact'],
                                        ['03/09/2021',
                                            'CANCELED',
                                            'Announcement',
                                            '(1:30 PM) (Judicial Officer Updegrove, '
                                            'Robert)',
                                            'Reset',
                                            'ARRG 12.09 REQ WOC'],
                                        ['04/29/2021',
                                            'CANCELED',
                                            'Announcement',
                                            '(8:30 AM) (Judicial Officer Updegrove, '
                                            'Robert)',
                                            'Reset'],
                                        ['06/17/2021',
                                            'CANCELED',
                                            'Announcement',
                                            '(1:30 PM) (Judicial Officer Updegrove, '
                                            'Robert)',
                                            'Reset'],
                                        ['06/25/2021', 'Discovery Receipt'],
                                        ['06/28/2021', 'Discovery Receipt'],
                                        ['08/16/2021', 'Discovery Receipt'],
                                        ['09/02/2021',
                                            'CANCELED',
                                            'Announcement',
                                            '(1:30 PM) (Judicial Officer Updegrove, '
                                            'Robert)',
                                            'Court'],
                                        ['10/27/2021',
                                            'Announcement',
                                            '(8:30 AM) (Judicial Officer Updegrove, '
                                            'Robert)']],
            'party information': {'SID': 'TX50762437',
                                'appointed or retained': 'Court Appointed',
                                'bondsman': '',
                                'bondsman address': '',
                                'date of birth': '04/18/1998',
                                'defendant': 'Daniels, Garrett Mitchell',
                                'defendant address': '6300 Linne Rd, Seguin, TX 78155',
                                'defense attorney': '145 lbs',
                                'defense attorney phone number': 'Court Appointed',
                                'height': '',
                                'prosecuting attorney': 'Melissa Pulido',
                                'prosecuting attorney address': '712 S Stagecoach TRL, '
                                                                'San Marcos, TX 78666',
                                'prosecuting attorney phone number': '',
                                'race': '',
                                'sex': 'Male',
                                'weight': ''}}